name: sprout_pokedex

packages:
  - "app_core/ai_gemini"
  - "app_core/app_preference"
  - "app_core/api"
  - "app_core/database"
  - "app_core/core"
  - "app_core/core_ui"
  - "features/feature_home"
  - "features/feature_detail"
  - "features/feature_chat"
  - "features/feature_chat_history"
  - "features/feature_set_ai_api_key"
  - "."

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  setup:
    description: "Complete project setup"
    run: |
      melos bootstrap
      melos run build:runner
      melos run icons
      melos run splash

  build:runner:
    description: "Run build_runner for all packages"
    run: |
      melos exec --depends-on="build_runner" "dart run build_runner build --delete-conflicting-outputs"

  clean:
    description: "Clean everything"
    run: |
      melos exec "flutter clean"
      rm -rf .melos_tool
      melos bootstrap

  upgrade:
    description: "Upgrade dependencies"
    run: |
      melos exec "flutter pub upgrade"
      melos bootstrap
